### ISSUE TITLE
Renew Time Not working?

### ISSUE THREAD

**Issue by benben10ten** [Dashactyl-Development/Dashactyl#8]
![image](https://user-images.githubusercontent.com/94194353/141524808-289f81a2-b46c-418e-93b3-eaa2c168557d.png)
![image](https://user-images.githubusercontent.com/94194353/141524862-b39971ed-d3d9-4e31-a7f9-4f09c533759e.png)

**Comment by Dviih** [comment]
If the server was manually created it won't work

**Comment by benben10ten** [comment]
![image](https://user-images.githubusercontent.com/94194353/141526170-8374d643-48b3-405b-8b51-f188431c769c.png)
It appears on the database, the server could not be created manually.

**Comment by JamieGrimwood** [comment]
Has not been commented on, and should have been fixed. If not please reopen.
